POST https://node-zero-os6v.onrender.com/videos
Content-Type: application/json

{
   "title":"Monter rock",
   "description":"This is the first video",
   "duration":120
}

###

GET https://node-zero-os6v.onrender.com/videos

###

PUT  https://node-zero-os6v.onrender.com/videos/9b9ba17f-0e28-414f-9e85-309a27ede9b1
Content-Type: application/json

{
   "title":"Monster Rodk",
   "description":"Welcome to battle",
   "duration":120
}

###

DELETE   https://node-zero-os6v.onrender.com/videos/1f15a8a8-05fb-4ec8-b54f-af8322a3bcfd
